"use client";
import { useEffect, useRef } from "react";
import type { HomeDay } from "@/data/home-days";
const SPACING = 64;
export function DayPicker({ activeDate, days, onSelect }: { activeDate: string; days: HomeDay[]; onSelect: (date: string) => void }) {
  const source = days;
  const index = Math.max(0, source.findIndex((day) => day.date === activeDate));
  const position = useRef(index), target = useRef(index), velocity = useRef(0), dragging = useRef(false), lastX = useRef(0), frame = useRef<number>(), refs = useRef<Array<HTMLButtonElement | null>>([]);
  useEffect(() => { target.current = index; }, [index]);
  useEffect(() => { const paint = () => { if (!dragging.current) { velocity.current = (velocity.current + (target.current - position.current) * .12) * .82; position.current += velocity.current; if (Math.abs(target.current - position.current) < .001 && Math.abs(velocity.current) < .001) { position.current = target.current; velocity.current = 0; } } refs.current.forEach((item, i) => { if (!item) return; const d = i - position.current, ad = Math.abs(d), visible = ad <= 2.05; item.style.left = `${d * SPACING}px`; item.style.transform = `translateX(-50%) scale(${.68 + .52 * Math.max(0, 1 - ad / 2)})`; item.style.opacity = visible ? `${Math.max(.12, 1 - ad * .34)}` : "0"; item.style.visibility = visible ? "visible" : "hidden"; item.style.pointerEvents = visible ? "auto" : "none"; item.style.filter = `blur(${Math.min(2.5, ad * 1.15)}px)`; item.setAttribute("aria-current", ad < .5 ? "date" : "false"); }); frame.current = requestAnimationFrame(paint); }; frame.current = requestAnimationFrame(paint); return () => { if (frame.current) cancelAnimationFrame(frame.current); }; }, []);
  const commit = (next: number) => { const safe = Math.max(0, Math.min(source.length - 1, next)); target.current = safe; onSelect(source[safe].date); };
  const down = (event: React.PointerEvent<HTMLDivElement>) => { dragging.current = true; velocity.current = 0; lastX.current = event.clientX; event.currentTarget.setPointerCapture(event.pointerId); };
  const move = (event: React.PointerEvent<HTMLDivElement>) => { if (!dragging.current) return; const delta = event.clientX - lastX.current; lastX.current = event.clientX; position.current = Math.max(0, Math.min(source.length - 1, position.current - delta / SPACING)); };
  const up = (event: React.PointerEvent<HTMLDivElement>) => { if (!dragging.current) return; dragging.current = false; if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); commit(Math.round(position.current)); };
  return <div aria-label="Utazás napjai" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} className="relative -mx-5 h-[118px] touch-none select-none overflow-hidden"><div className="absolute left-1/2 top-1/2 h-[88px] w-0 -translate-y-1/2">{source.map((day, i) => <button key={day.date} ref={(el) => { refs.current[i] = el; }} type="button" aria-label={`${day.weekday}, szeptember ${day.day}`} onClick={(event) => { event.stopPropagation(); position.current = i; velocity.current = 0; commit(i); }} className="absolute top-[9px] w-16 border-0 bg-transparent p-0 text-center [will-change:transform,opacity,filter]"><span className="flex min-h-[70px] flex-col items-center justify-center"><span className="text-[32px] font-bold leading-none tracking-[-.04em]">{day.day}</span><span className={`mt-[3px] text-[13px] font-medium leading-none ${day.weekday === "Vas" ? "text-coral" : "text-deep-sea/60"}`}>{day.weekday}</span></span></button>)}</div></div>;
}
